# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4lcTznM4_rKAuT9KmcRwApN6u5wBI0Y
"""

import numpy as np
from src.utils import load_model
from src.train import load_data

if __name__ == "__main__":
    model = load_model("linear_model.joblib")
    _, X_test, _, _ = load_data()

    preds = model.predict(X_test[:5])
    print("Sample Predictions:", preds)