name: MLOps Assignment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest tests/ -v

  train_and_quantize:
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train and quantize
        run: |
          python -m src.train
          python -m src.quantize
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models/

  build_and_test_container:
    runs-on: ubuntu-latest
    needs: train_and_quantize
    steps:
      - uses: actions/checkout@v4

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Build Docker image
        run: docker build -t mlops-assignment .

      - name: Test container
        run: docker run --rm mlops-assignment
